spring:
  profiles:
    active: docker
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/thesis
  redis:
    port: 6379
    host: redis
  application:
    name: user-serve

logging:
  level:
    com.micro.userserve: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.micro.userserve.*.entity
server:
  port: 10002
grpc:
  server:
    port: 9090
  client:
    role-serve:
      address: static://localhost:9091
      negotiation-type: plaintext

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7887/eureka/
  instance:
    prefer-ip-address: true