server:
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: role-serve
          uri: lb://ROLE-SERVE
          predicates:
            - Path=/role/**
        - id: user-service # 路由标示，必须唯一
          uri: lb://USER-SERVE
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/**,/menu/**
        - id: conferences-service
          uri: lb://CONFERENCE-SERVE
          predicates:
            - Path=/conferences/**,/invite/**,/pcMembers/**
        - id: paper-service
          uri: lb://PAPER-SERVE
          predicates:
            - Path=/papers/**,/review/**
  zipkin:
    baseUrl: http://zipkin:9411/

logging:
  level:
    com:
      micro:
        gateway: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:7887/eureka/
  instance:
    prefer-ip-address: true